postgresql:
  version: 9.5
  postgis_version: 2.2

  user: postgres
  group: postgres

  config:
    shared_buffers: 24MB
    work_mem: 1MB

    checkpoint_segments: 3
    checkpoint_completion_target: 0.5

    effective_cache_size: 128MB
